name: advance_pdf_viewer
description: A flutter plugin for handling PDF files. Works on both Android & iOS
version: 1.1.6
homepage: https://github.com/lohanidamodar/pdf_viewer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^1.1.3
  path_provider: ^1.6.5
  numberpicker: ^1.2.0
  flutter_advanced_networkimage: 
    git:
      url: https://github.com/mchome/flutter_advanced_networkimage

flutter:
  plugin:
    androidPackage: pt.tribeiro.flutter_plugin_pdf_viewer
    pluginClass: FlutterPluginPdfViewerPlugin
